### ISSUE TITLE
Multiple annotations

### ISSUE THREAD

**Issue by ghost** [gierschv/GoogleAnalytics-AnnotationsManager#1]
Hi Vincent,  

There was some difficulty experienced when copying more than one annotation at a time.  It was done using Firefox v17.0.1.  In the example of two annotations, the copy and local storage occurred ok and after the paste action button was clicked, both were inserted into the interface chart.  However, when navigating away and viewing the annotation on a different report, the second annotation had been erased.  This observation occurred on several attempts using different profiles.

Is this a known issue?

Thanks,
Alex

p.s. Allow me to say how grateful I am that you created this time saving profile annotation copier.  It definitely makes life a lot easier - even using one annotation at a time copy - paste.

**Comment by gierschv** [comment]
Hello,

Thanks for your feedback: it seems to be a new issue from GA: the actions are done and applied in the user interface but GA send only one HTTP request by one.

I'll try to patch it when I will have some time.

Vincent

**Comment by ghost** [comment]
Thanks, Vincent!!
